version: '3'
services:
    web:
        image: magento2
        container_name: web
        restart: always
        volumes:
          - E:\Docker\Magento\magento:/var/www/html/:cached
        ports:
          - "8090:80"
          - "443:443"
        links:
          - mysql
    mysql:
        image: mysql:5.6
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
          - MYSQL_USER=masteradmin
          - MYSQL_PASSWORD=B5x26z4p=
        volumes:
          - db-data:/var/lib/mysql
        command: --innodb-use-native-aio=0

volumes:
    db-data:
        external: false