FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt  update

RUN apt install -y software-properties-common
RUN apt-add-repository ppa:ondrej/php

RUN apt install -y apache2 \
					php7.1 \
					php7.1-cli \
					php7.1-common  \
					php7.1-json  \
					php7.1-opcache \ 
					php7.1-mysql \ 
					php7.1-mbstring  \
					php7.1-mcrypt \ 
					php7.1-zip  \
					php7.1-fpm \ 
					php7.1-soap \ 
					php7.1-intl \ 
					php7.1-xml \ 
					php7.1-curl \ 
					php7.1-zip \
					libapache2-mod-php7.1 \
					php7.1-bcmath \
					php7.1-gd

RUN a2enmod php7.1
RUN a2enmod rewrite

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid


EXPOSE 80

ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

CMD /usr/sbin/apache2ctl -D FOREGROUND